name: Automated Update README

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - .github/workflows/aotumatedUpdateReadme.yml

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - name: github-update-readme-V2.0
        uses: Ligengxin96/github-update-readme@v1.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_README }}
        with:
          showTrafficData: true
          header: About FetchRepooTrafficData
          subhead: |
                  This project can fetch specific repo everyday traffic data and save in the MongoDB
                  
                  ## Last 14 days repo traffic data

                  Total views data: `'{viewsData}'`

                  Total clones data: `'{clonesData}'`
                  
                  ## Latest fetch images time
                  
                  Latest fetch data time: `${{ steps.date.outputs.date }}`
                  
                  ## To everyone
                  
                  If this project is helpful to you please star this project, this is an encouragement to me `:)`

