name: Automated Update README

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - .github/workflows/automatedUpdateReadme.yml

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
  
      - name: UpdateReadmeAction-Private
        uses: Ligengxin96/UpdateReadmeAction-Private@v1.0-private-dogfood
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_README }}
        with:
          showTrafficData: true
          apiPath: https://getrepootrafficdata.herokuapp.com/v1/getrepoinfo
          header: About FetchRepoTrafficData
          subhead: |
                  The `main` branch project can fetch specific repo everyday traffic data and save in the MongoDB.

                  The `apis` branch project can expose the apis so that we can get our repo historical traffic data.
                  
                  ## `'{startDate}'` To `'{endDate}'` '{repo}' repo traffic data

                  Total views data: `'{viewsData}'`

                  Total clones data: `'{clonesData}'`
                  
                  ## Latest fetch images time
                  
                  Latest fetch data time: `${{ steps.date.outputs.date }}`
                  
                  ## To everyone
                  
                  If this project is helpful to you please star this project, this is an encouragement to me `:)`

