name: Deploy Get Repoo Traffic Data Server To Heroku

on:
  push:
    branches:
      - apis
    paths-ignore: 
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy To Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "getrepootrafficdata"
          heroku_email: "ligengxin96@gmail.com"
